name: Build Launcher

on:
  push:
    branches: [ 'dev-**', 'pr-**', staging, master ]
    tags: [ '**' ]
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - '*.md'
  pull_request:
    branches: [ staging, master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout the full history (required for GitVersion to work)
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install NSIS
      - name: Install NSIS
        run: choco install nsis -y
      - name: Print NSIS version
        run: makensis -VERSION
      - name: Print NSIS compile flags
        run: makensis -HDRINFO

      # Install libsqlite3
      - name: install sqlite
        run: choco install sqlite

      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Display Python version
        run: python --version

      # Install build local dependencies
      - name: Build
        shell: pwsh
        run: |
          .\scripts\install-deps.ps1

      # Execute project build script
      - name: Build
        id: build-step
        shell: pwsh
        run: |
          .\scripts\build.ps1
          $semVer = build\gitversion\gitversion.exe /showvariable SemVer
          Write-Output "::set-output name=BUILD_VERSION::$semVer"

      # Publish artifacts built in this pipeline
      - uses: actions/upload-artifact@v3
        with:
          name: UnmanicLauncherInstaller-${{ steps.build-step.outputs.BUILD_VERSION }}
          path: build\nsis\UnmanicLauncher*.exe
