name: Build Launcher for Linux

on:
  push:
    branches: [ 'dev-**', 'pr-**', staging, master ]
    tags: [ '**' ]
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - '*.md'
  pull_request:
    branches: [ staging, master ]

jobs:
  BuildAppImage:
    runs-on: ubuntu-20.04
    steps:
      # Checkout the full history (required for GitVersion to work)
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          # Build AppImage with Python 3.8 (same as the output will be)
          python-version: 3.8
      - name: Display Python version
        run: python --version

      # Restore build dependencies cache
      - name: Restore build dependencies cache
        uses: actions/cache@v3
        with:
          path: build/dependencies
          key: ${{ runner.os }}-build-dependencies-lin-${{ hashFiles('build/dependencies/**') }}
          restore-keys: |
            ${{ runner.os }}-build-dependencies-lin-

      # Install build local dependencies
      - name: Install build dependencies
        run: |
          ./scripts/install-tools-linux.sh
          sudo apt-get install -y pkg-config libcairo2-dev gcc python3-dev libgirepository1.0-dev

      # Execute project build script
      - name: Build
        id: build-step
        shell: pwsh
        run: |
          ./scripts/build-linux.sh
          $semVer=build/tools/gitversion/gitversion /showvariable SemVer
          mv -v build/UnmanicLauncher-x86_64.AppImage build/UnmanicLauncher-${semVer}-x86_64.AppImage 
          echo "::set-output name=BUILD_VERSION::${semVer}"

      # Publish artifacts built in this pipeline
      - uses: actions/upload-artifact@v3
        with:
          name: UnmanicLauncher-${{ steps.build-step.outputs.BUILD_VERSION }}-x86_64.AppImage
          path: build/UnmanicLauncher-${{ steps.build-step.outputs.BUILD_VERSION }}-x86_64.AppImage
